Repository servicemesher/istio-handbook, pull requests merged in 2019-04, with the labels that each got.

#22 Update envoy-ads.md
  data-plane/envoy-ads.md
Labels: kind/style

#21 Add circuit-breaking-and-outlier-detection-in-istio.md
  SUMMARY.md
  traffic-management/circuit-breaking-and-outlier-detection-in-istio.md
Labels: new/page

#25 从边车模式到 Service Mesh
  SUMMARY.md
  concepts-and-principle/sidercar-to-servicemesh.md
Labels: new/page

#26 fix: 修正 “常见 iptables 使用规则场景整理” 第三方网站链接的URL
  concepts-and-principle/sidecar-injection-deep-dive.md
Labels: kind/link
