Repository servicemesher/istio-handbook, pull requests merged in 2020-04, with the labels that each got.

#179 增加《服务网格概述篇》
  concepts/overview.md
Labels: approved, size/M

#181 Add images spec
  wg/specification.md
Labels: approved, lgtm, size/M

#177 concepts/traffic-shadow,镜像流量概念介绍
  concepts/traffic-shadow.md
  images/concepts-traffic-shadow-01.png
  images/concepts-traffic-shadow-header.png
  images/concepts-traffic-shadow-request.png
Labels: approved, size/L

#180 add: OpenTracing introduction
  practice/images/enhance-tracing-eshop-demo.jpg
  practice/images/enhance-tracing-istio-tracing-opentracing-in-depth-method.jpg
  practice/images/enhance-tracing-istio-tracing-opentracing-in-depth.jpg
  practice/images/enhance-tracing-istio-tracing-opentracing.jpg
  practice/images/enhance-tracing-istio-tracing.jpg
  practice/images/enhance-tracing-monolith-microserivce.jpg
  practice/images/enhance-tracing-tracing_mental_model.png
  practice/opentracing.md
Labels: approved, size/L

#187 update: opentracing
  SUMMARY.md
  concepts/microservices-in-post-kubernetes-era.md
  images/enhance-tracing-monolith-microserivce.jpg
  images/enhance-tracing-tracing_mental_model.png
  practice/distributed-tracing.md
  practice/images/enhance-tracing-eshop-demo.jpg
  practice/images/enhance-tracing-istio-tracing-opentracing-in-depth-method.jpg
  practice/images/enhance-tracing-istio-tracing-opentracing-in-depth.jpg
  practice/images/enhance-tracing-istio-tracing-opentracing.jpg
  practice/images/enhance-tracing-istio-tracing.jpg
  practice/katacoda.md
  practice/opentracing.md
Labels: approved, size/L

#186 add: practice/jwt-authorization
  practice/jwt-authorization.md
Labels: approved, size/XL

#193 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/XS

#195 update: 更新部分文中的错误
  concepts/overview.md
  practice/distributed-tracing.md
  practice/opentracing.md
Labels: approved, lgtm, size/S

#182 add: Istio handbook glossary
  GLOSSARY.md
Labels: approved, size/L

#194 add:安装与部署
  practice/setup.md
Labels: approved, size/XS

#183 update: Pilot: concepts/pilot.md
  concepts/pilot.md
  images/pilot-arch.png
  images/pilot.png
Labels: approved, size/L

#184 Service Mesh 生态：ecosystem/overview.md
  ecosystem/overview.md
Labels: size/L

#198 delete:移除虚拟机部署章节
  SUMMARY.md
  practice/multiple-environments.md
  practice/setup-in-kubernetes.md
  practice/setup-in-vm.md
Labels: approved, lgtm, size/S

#199 update: add katacoda quick start
  README.md
  images/katacoda-logo.png
Labels: approved, size/S

#200 update: mergify config
  .mergify.yml
Labels: approved, size/XS

#201 add:安装 Istio
  practice/setup-istio.md
Labels: approved, size/L

#202 delete:Kubernetes 部署
  SUMMARY.md
  practice/setup-in-kubernetes.md
Labels: approved, size/XS

#197 add: 方法级调用跟踪
  GLOSSARY.md
  SUMMARY.md
  images/enhance-tracing-eshop-demo.jpg
  images/enhance-tracing-istio-tracing-opentracing-in-depth-method.jpg
  images/enhance-tracing-istio-tracing-opentracing-in-depth.jpg
  images/enhance-tracing-istio-tracing-opentracing.jpg
  images/enhance-tracing-istio-tracing.jpg
  practice/kafka-tracing.md
  practice/method-level-tracing.md
  practice/opentracing.md
Labels: approved, size/XL

#176 add: concepts/fault-injection 故障注入概念
  concepts/fault-injection.md
  images/concepts-fault-inject-abort.png
  images/concepts-fault-inject-delay.png
  images/concepts-no-fault-inject.png
Labels: approved, do-not-merge/hold, size/L

#203 add: 数据面MOSN概念介绍
  concepts/mosn.md
  images/concepts-mosn-arch.png
  images/concepts-mosn-connpool.png
  images/concepts-mosn-feature.png
  images/concepts-mosn-goroutine.png
  images/concepts-mosn-istio.png
  images/concepts-mosn-mempool.png
Labels: approved, size/M

#210 update: replace some images
  concepts/mosn.md
  images/concepts-mosn-goroutine.png
  images/concepts-mosn-istio.png
  images/concepts-mosn-mempool.png
  images/mosn-goroutine-model.jpg
  images/mosn-istio.png
  practice/setup-istio.md
Labels: approved, size/L

#207 add: 架构解析
  concepts/architecture-overview.md
  images/istio-arch-evolution.png
Labels: approved, size/M

#209 add:入门实践/流量控制/超时:practice/timeout.md
  images/bookinfo-virtual-service-reviews-timeout.png
  images/bookinfo-virtual-service-reviews-v2.png
  practice/setup-istio.md
  practice/timeout.md
Labels: approved, size/L

#208 add: practice/kafka-tracing.md #171
  images/enhance-tracing-eshop-demo-kafka.jpg
  images/enhance-tracing-istio-tracing-opentracing-kafka-rest.jpg
  images/enhance-tracing-istio-tracing-opentracing-kafka.jpg
  images/enhance-tracing-trace-graph.jpg
  images/eshop-demo-kafka.jpg
  practice/kafka-tracing.md
Labels: approved, size/L

#218 add: sidecar 注入和流量透明劫持
  SUMMARY.md
  concepts/sidecar-injection.md
  images/envoy-sidecar-traffic-interception.png
  images/sidecar-pattern.jpg
Labels: approved, size/XL

#220 update: 删除流量路由部分
  concepts/sidecar-injection.md
Labels: approved, size/L
