Repository servicemesher/istio-handbook, pull requests merged in 2020-03, with the labels that each got.

#52 TOC v0.3: add xDS and multi-cluster deployment model
  wg/mind-map.mindnode/QuickLook/Preview.jpg
  wg/mind-map.mindnode/contents.xml
  wg/mind-map.mindnode/style.mindnodestyle/contents.xml
  wg/mind-map.mindnode/viewState.plist
  wg/mind-map.png
  wg/toc.md
Labels: size/S

#163 增加社区参与流程介绍
  README.md
  SUMMARY.md
  images/istio-handbook-process.jpg
  images/servicemesher-qr-code.jpg
  wg/process.md
Labels: approved, size/L

#164 增加 Gitbook 配置用于 netlify 预览
  package.json
  wg/process.md
Labels: approved, lgtm, size/M

#165 Catalog
  README.md
Labels: size/XS

#166 增加版权许可说明
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSE
  README.md
  wg/specification.md
Labels: approved, lgtm, size/XL

#167 完善日志管理技术栈
  SUMMARY.md
  practice/efk.md
Labels: size/XS

#172 Update process.md
  wg/process.md
Labels: lgtm

#174 实践篇:katacoda
  images/katacoda-configuration.jpg
  images/katacoda-course.jpg
  images/katacoda-detail.jpg
  images/katacoda-profile.jpg
  practice/katacoda.md
Labels: approved, do-not-merge/hold, lgtm, size/L

#178 refine spec
  wg/specification.md
Labels: approved, lgtm, size/S

#175 Service Mesh 在云原生中的应用
  SUMMARY.md
  book.json
  concepts/microservices-in-post-kubernetes-era.md
  concepts/within-cloud-native.md
  images/envoy-arch.png
  images/istio-mesh-arch.png
  images/istio-service-registry.png
  images/kubernetes-vs-service-mesh.png
  images/service-mesh-schematic-diagram.png
  images/xds-protocol.png
Labels: approved, lgtm, size/L
