Repository servicemesher/istio-handbook, pull requests merged in 2020-07, with the labels that each got.

#284 cmt feature
  concepts/features.md
Labels: approved, size/M

#279 Add: practice/zipkin.md
  images/zipkin-architecture.png
  images/zipkin-bookinfo.png
  images/zipkin-dashboard.png
  images/zipkin-principle.png
  images/zipkin-user-invoke-link.png
  practice/zipkin.md
Labels: approved, size/L

#253 add: VirtualService
  practice/route.md
Labels: size/L

#285 update：作者列表
  README.md
Labels: approved, lgtm, size/XS

#286 Add:多集群部署与管理
  images/multicluster-with-gateways.svg
  images/multicluster-with-vpn.svg
  practice/multiple-cluster.md
Labels: approved, size/L

#287 Add : practice/jaeger.md
  SUMMARY.md
  images/envoy-jaeger.png
  images/jaeger-architecture.png
  images/jaeger-compare.png
  images/jaeger-dashboard.png
  images/jaeger-dependencies.png
  images/jaeger-detail.png
  images/jaeger-trace-span.png
  images/jaeger-traces.png
  practice/jaeger.md
  practice/jeager.md
Labels: size/L

#259 add: ecosystem/xds.md
  ecosystem/xds.md
  images/xds-ack.png
  images/xds-envoy-pilot-flow.png
  images/xds-incremental-reconnect.png
  images/xds-incremental.png
  images/xds-nack.png
  images/xds-pilot-envoy.png
Labels: size/L
