Repository servicemesher/istio-handbook, pull requests merged in 2020-06, with the labels that each got.

#228 add: concepts/observability
  concepts/observability.md
Labels: size/M

#264 add: concepts/basic.md
  concepts/basic.md
  concepts/overview.md
Labels: approved, size/L

#266 add：集成服务注册中心
  SUMMARY.md
  images/pilot-service-model.svg
  images/pilot-services-source.svg
  images/service-registry-integration.svg
  practice/integration-registry.md
Labels: approved, size/L

#270 fix：目录调整
  SUMMARY.md
  practice/authorization-policy.md
  practice/eureka.md
  wg/mind-map.mindnode/QuickLook/Preview.jpg
  wg/mind-map.mindnode/contents.xml
  wg/mind-map.mindnode/viewState.plist
  wg/mind-map.png
Labels: approved, size/S

#273 Add: concept/envoy
  concepts/envoy.md
  images/concept-envoy-filter.png
  images/concept-envoy-roles.png
  images/concept-envoy-thread.png
  images/concept-envoy-xds.png
  images/concepts-envoy-arch-simple.png
Labels: size/L

#265 add: concepts/data-plane.md
  concepts/data-plane.md
  images/concepts-data-plane-arch.png
  images/concepts-data-plane-overview.png
Labels: size/M

#256 add: prictice traffic control
  images/istio-traffic-arch.png
  practice/traffic-control.md
Labels: size/L

#274 add: practice/efk.md
  images/efk-stack.png
  images/kibana-query-log.png
  images/kubernetes-log-basis.png
  images/setup-index.png
  practice/efk.md
Labels: approved, lgtm, size/XL

#276 update：作者列表
  README.md
Labels: lgtm, size/XS

#277 update：作者列表
  README.md
Labels: approved, lgtm, size/XS

#281 Update microservices-in-post-kubernetes-era.md
  concepts/microservices-in-post-kubernetes-era.md
Labels: size/XS

#282 fix basic.md
  concepts/basic.md
Labels: approved, size/XS
