Repository servicemesher/istio-handbook, pull requests merged in 2020-05, with the labels that each got.

#224 add:concepts/log, update:practice/opentracing
  concepts/log.md
  images/concepts-log-landscape.jpg
  practice/opentracing.md
Labels: size/S

#221 add:入门实践/流量控制/重试
  practice/retry.md
  practice/timeout.md
Labels: approved, area/practice, size/L

#217 add：诊断工具
  SUMMARY.md
  images/diagnostic-tools-controlz-index.png
  images/diagnostic-tools-controlz-logging.png
  practice/controlz-tool.md
  practice/diagnostic-tools.md
  practice/istioctl-cmd-tool.md
Labels: size/XL

#214 practice/traffic-shadow
  images/shadow-in-one-mesh.png
  images/shadow-in-two-mesh.png
  practice/traffic-shadow.md
Labels: approved, size/L

#232 update：作者列表
  README.md
Labels: approved, lgtm, size/XS

#190 add:bookinfo应用初稿
  images/Bookinfo-Application-without-Istio.png
  images/Bookinfo-Application.png
  practice/bookinfo.md
Labels: approved, do-not-merge/hold, size/L

#234 update：作者列表
  README.md
Labels: approved, size/XS

#236 Bookinfo linda01232003
  practice/bookinfo.md
Labels: lgtm, size/M

#238 update: pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/S

#227 add: ecosystem/webassembly
  ecosystem/webassembly.md
  images/ecosystem-webassembly-envoy.png
  images/ecosystem-webassembly-mixer.png
Labels: approved, size/M

#239 update：作者列表
  README.md
Labels: approved, lgtm, size/XS

#231 add: Sidecar 流量路由机制分析
  SUMMARY.md
  concepts/sidecar-traffic-route.md
  images/envoy-config-init.png
  images/envoy-traffic-route.jpg
Labels: approved, lgtm, size/XXL

#235 add: concepts/ServiceEntry
  concepts/serviceentry.md
Labels: approved, size/L

#244 add: ecosystem/smi
  ecosystem/smi.md
  images/ecosystem-smi-ecosystem.png
  images/ecosystem-smi-friends.png
  images/ecosystem-smi-what-is.png
Labels: approved, lgtm, size/M

#246 fix: concept/overview
  concepts/overview.md
Labels: approved, size/XS

#248 update: catalogue [add: concepts/sidecar.md | move: concepts/sidecar-t…
  SUMMARY.md
  concepts/sidecar.md
Labels: approved, size/XS

#225 add: practice/mutual-tls.md
  images/authz.png
  images/istio-mutual-simple-test.jpg
  images/mtls-handshake-parti.jpg
  images/mtls-handshake-partii.jpg
  images/mtls-handshake-partiii.jpg
  practice/matual-tls.md
Labels: approved, do-not-merge/hold, size/L

#243 add:常见问题
  images/faq-app-port.png
  images/faq-b3-headers.png
  images/faq-default-gateway.png
  images/faq-envoy-log.png
  images/faq-envoy-model.png
  images/faq-gateway-port.png
  images/faq-log-nr.png
  images/faq-log-ok.png
  images/faq-log-uh.png
  images/faq-port-naming.png
  images/faq-request-fanout.png
  images/faq-sidecar-order.png
  images/faq-sidecar-type.png
  images/faq-tracing.png
  images/faq-vs-chaining.png
  images/faq-xds-order.png
  images/fqa-log-uf.png
  practice/faq.md
Labels: do-not-merge/hold, size/L

#249 update：作者列表
  README.md
Labels: approved, lgtm, size/XS

#252 fix：目录调整
  SUMMARY.md
  concepts/authentication-arch.md
  concepts/authentication-policy.md
  concepts/authentication.md
  concepts/authorization-arch.md
  concepts/authorization-policy.md
  concepts/authorization.md
  concepts/circuit-breaking.md
  concepts/destinationrule.md
  concepts/distributed-tracing.md
  concepts/fault-injection.md
  concepts/gateway.md
  concepts/log.md
  concepts/metrics.md
  concepts/resilience-test.md
  concepts/retry.md
  concepts/route.md
  concepts/serviceentry.md
  concepts/timeout.md
  concepts/traffic-shadow.md
  concepts/virtualservice.md
  practice/authentication-policy.md
  practice/authorization-policy.md
  practice/deny-authorization.md
  practice/end-users-authentication.md
  practice/fault-injection.md
  practice/http-traffic-authorization.md
  practice/logging.md
  practice/mesh-to-mesh-authentication.md
  practice/peer-authentication.md
  practice/request-authentication.md
  practice/route.md
  practice/tcp-traffic-authorization.md
  practice/traffic-shadow.md
  wg/mind-map.mindnode/QuickLook/Preview.jpg
  wg/mind-map.mindnode/contents.xml
  wg/mind-map.mindnode/style.mindnodestyle/contents.xml
  wg/mind-map.mindnode/viewState.plist
  wg/mind-map.png
Labels: approved, lgtm, size/XL

#254 fix:目录结构
  SUMMARY.md
  wg/mind-map.mindnode/QuickLook/Preview.jpg
  wg/mind-map.mindnode/contents.xml
  wg/mind-map.mindnode/viewState.plist
  wg/mind-map.png
  wg/toc.md
Labels: approved, lgtm, size/L

#258 update：setup istio
  practice/setup-istio.md
Labels: approved, size/XS

#261 Add：入门实践
  practice/primer.md
Labels: approved, size/XS
